name: upload my image to DockerHub

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create docker image
        run: echo Hello, world!

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/calculator:latest

      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/calculator:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            sudo docker stop calc
            sudo docker rm calc
            sudo docker rmi elieyal2/calculator
            sudo docker pull elieyal2/calculator
            sudo docker run --name calc -d -p 80:3000 elieyal2/calculator